script:
- npm install asar -g
- npm install
- npm install bower grunt -g
- bower install
- grunt init
- "./build.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XBFe4blDrYEEmZEx7izWva6jA074gLRhmMuCLyg8/rK+z7UauERtJdqQzVZjn3mvpjedE4BssoaftZ34lLE5KLa0dT8rYoatSfLL/SEzKanHNZOA1z5S3+zXck8h+UrdZLYmXDUvF/xmjuPxHzWquU+9pCw3tlmhxWJNy0nYDxHAbOgNahoIE5eAJoe1mbhxziDddPUqMsMWx2Uj5ici8cBbsmRjjr8DmIH/9Gr9sv9ELun1EHMdYsOYY+P4gZrQzRXMdQGFXFF5eD2H8ClOE0OhvxpmBYF5dWshg9YCQQFoe145ra2GpybdLa9yIQI4IGV8QmVx9cDqFOECLDPVNuXUgpdPNWRPLXmMV3OKF63x5RCzfAIbsIM3OkJ68213PjY4M+xIR+Eqo57PgcVg2EiDYuIhfcL9xcDL3BTBy05rwxWerm2rzMx/S05ST/R7ILtz3cbnW26XZMDxL2pSorIPv8sISeNgbJcuPpgzX/LzK4ksjWYNqFG2bTtvFFDHr7/04IE0L3WDf1jBYKxdcN37fVL0sug3iHuj2hZyVwbxWyBICON8E/k03VWvtWuBbaltTg0o6M6XUs/RHzC9khwz7D1WjUuV2aTt0LpnPcVEtJIG++dxQu4TLfTwmB4J5u5pIsBQKrEYZbUlzJF26ReSlNypPEQrXkx5zV3V6MQ=
  file: 
    - "./build/app.asar"
    - "./build/party-youtube-downloader-darwin.zip"
    - "./build/party-youtube-downloader-linux-ia32.zip"
    - "./build/party-youtube-downloader-linux-x64.zip"
    - "./build/party-youtube-downloader-windows-ia32.zip"
    - "./build/party-youtube-downloader-windows-x64.zip"
  on:
    repo: nemanjan00/party-youtube-downloader
    all_branches: true
    tags: true

